export const ONBOARDING_STEPS = [
  { number: 1, slug: "business", title: "Business Basics" },
  { number: 2, slug: "goals", title: "Campaign Goals" },
  { number: 3, slug: "targeting", title: "Geographic Targeting" },
  { number: 4, slug: "keywords", title: "Keywords & Audience" },
  { number: 5, slug: "budget", title: "Budget" },
  { number: 6, slug: "ad-copy", title: "Ad Copy" },
  { number: 7, slug: "review", title: "Review & Submit" },
] as const;

export const INDUSTRIES = [
  "Automotive",
  "Beauty & Wellness",
  "Construction",
  "Consulting",
  "Dental",
  "Education",
  "Electrical",
  "Financial Services",
  "Fitness & Gym",
  "Healthcare",
  "Home Services",
  "HVAC",
  "Insurance",
  "Interior Design",
  "IT Services",
  "Landscaping",
  "Legal",
  "Medical",
  "Moving & Storage",
  "Pest Control",
  "Photography",
  "Plumbing",
  "Real Estate",
  "Restaurant & Food",
  "Retail",
  "Roofing",
  "Solar",
  "Travel & Tourism",
  "Veterinary",
  "Other",
] as const;

export const CAMPAIGN_GOALS = [
  { value: "leads", label: "Generate Leads", description: "Get form submissions and inquiries" },
  { value: "calls", label: "Get Phone Calls", description: "Drive calls to your business" },
  { value: "traffic", label: "Drive Website Traffic", description: "Bring more visitors to your site" },
  { value: "sales", label: "Increase Online Sales", description: "Boost e-commerce revenue" },
  { value: "brand_awareness", label: "Build Brand Awareness", description: "Get your name out there" },
] as const;

export const PREDEFINED_CTAS = [
  "Call Now",
  "Get a Free Quote",
  "Book Online",
  "Learn More",
  "Shop Now",
  "Schedule Today",
  "Request a Consultation",
  "Contact Us",
] as const;

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
] as const;

export const KEYWORD_SUGGESTIONS: Record<string, string[]> = {
  "Plumbing": ["plumber near me", "emergency plumber", "plumbing repair", "water heater installation", "drain cleaning"],
  "Legal": ["lawyer near me", "personal injury attorney", "family law attorney", "criminal defense lawyer", "estate planning attorney"],
  "Dental": ["dentist near me", "teeth whitening", "dental implants", "emergency dentist", "family dentist"],
  "HVAC": ["hvac repair near me", "ac installation", "furnace repair", "heating and cooling", "hvac maintenance"],
  "Roofing": ["roofing contractor", "roof repair near me", "roof replacement", "roof inspection", "emergency roof repair"],
  "Real Estate": ["homes for sale near me", "real estate agent", "buy a house", "sell my house fast", "realtor near me"],
  "Home Services": ["handyman near me", "home repair", "house cleaning", "home renovation", "home improvement"],
  "Restaurant & Food": ["restaurant near me", "best food near me", "catering services", "food delivery", "private dining"],
  "Automotive": ["auto repair near me", "car mechanic", "oil change", "brake repair", "tire shop"],
  "Healthcare": ["doctor near me", "urgent care", "primary care physician", "family doctor", "walk-in clinic"],
};
